# Data for biblical travel journeys
biblical_travel_data = [
    # Old Testament Journeys
    {
        "journey": "Abraham's journey to Canaan",
        "source_name": "Ur of the Chaldeans",
        "destination_name": "Canaan",
        "lat_long_source": [30.58, 47.8],
        "lat_long_destination": [32.08, 35.17],
        "distance_km": 1500,
        "timeframe": "~2000 BC",
        "people_involved": "Abraham, Sarah, Lot",
        "scripture_reference": "Genesis 12:1-9",
    },
    {
        "journey": "Exodus from Egypt",
        "source_name": "Egypt",
        "destination_name": "Canaan",
        "lat_long_source": [30.04, 31.23],
        "lat_long_destination": [32.08, 35.17],
        "distance_km": 400,
        "timeframe": "~1446 BC (est.)",
        "people_involved": "Moses, Israelites (~600,000 men)",
        "scripture_reference": "Exodus 12–14",
    },
    {
        "journey": "Jacob's journey to Egypt",
        "source_name": "Canaan",
        "destination_name": "Egypt",
        "lat_long_source": [32.08, 35.17],
        "lat_long_destination": [30.04, 31.23],
        "distance_km": 400,
        "timeframe": "~1876 BC",
        "people_involved": "Jacob, Joseph, family",
        "scripture_reference": "Genesis 46:1-7",
    },
    {
        "journey": "Elijah's journey to Mount Horeb",
        "source_name": "Beersheba",
        "destination_name": "Mount Horeb",
        "lat_long_source": [31.25, 34.79],
        "lat_long_destination": [28.54, 34.83],
        "distance_km": 450,
        "timeframe": "~9th Century BC",
        "people_involved": "Elijah",
        "scripture_reference": "1 Kings 19:3-8",
    },
    {
        "journey": "David's journey to Hebron",
        "source_name": "Ziklag",
        "destination_name": "Hebron",
        "lat_long_source": [31.26, 34.8],
        "lat_long_destination": [31.53, 35.1],
        "distance_km": 35,
        "timeframe": "~1000 BC",
        "people_involved": "David, family, followers",
        "scripture_reference": "2 Samuel 2:1-4",
    },
    {
        "journey": "Jonah's Journey to Nineveh",
        "source_name": "Joppa",
        "destination_name": "Nineveh",
        "lat_long_source": [32.05, 34.75],
        "lat_long_destination": [36.34, 43.13],
        "distance_km": 800,
        "timeframe": "Unknown",
        "people_involved": "Jonah",
        "scripture_reference": "Jonah 1–4",
    },
    # New Testament Journeys
    {
        "journey": "Joseph and Mary to Egypt",
        "source_name": "Bethlehem",
        "destination_name": "Egypt",
        "lat_long_source": [31.7054, 35.2024],
        "lat_long_destination": [29.8587, 31.1460],
        "distance_km": 300,
        "timeframe": "~4 BCE",
        "people_involved": "Joseph, Mary, Jesus",
        "scripture_reference": "Matthew 2:13-15",
    },
    {
        "journey": "Joseph and Mary's Journey to Bethlehem",
        "source_name": "Nazareth",
        "destination_name": "Bethlehem",
        "lat_long_source": [32.7, 35.3],
        "lat_long_destination": [31.7, 35.2],
        "distance_km": 130,
        "timeframe": "~4-6 BCE",
        "people_involved": "Joseph, Mary",
        "scripture_reference": "Luke 2:1-7",
    },
    {
        "journey": "Jesus' Journey to Jerusalem",
        "source_name": "Galilee",
        "destination_name": "Jerusalem",
        "lat_long_source": [32.7, 35.3],
        "lat_long_destination": [31.78, 35.2],
        "distance_km": 200,
        "timeframe": "~30 AD",
        "people_involved": "Jesus, disciples, crowds",
        "scripture_reference": "Gospels",
    },
    {
        "journey": "Jesus' visit to Samaria",
        "source_name": "Judea",
        "destination_name": "Samaria",
        "lat_long_source": [31.78, 35.2],
        "lat_long_destination": [32.22, 35.25],
        "distance_km": 65,
        "timeframe": "~27-30 AD",
        "people_involved": "Jesus, disciples",
        "scripture_reference": "John 4:1-42",
    },
    {
        "journey": "Paul's First Missionary Journey",
        "source_name": "Antioch (Syria)",
        "destination_name": "Derbe",
        "lat_long_source": [36.2, 36.16],
        "lat_long_destination": [37.6, 34.07],
        "distance_km": 500,
        "timeframe": "~46–48 AD",
        "people_involved": "Paul, Barnabas",
        "scripture_reference": "Acts 13–14",
    },
    {
        "journey": "Paul's Second Missionary Journey",
        "source_name": "Jerusalem",
        "destination_name": "Corinth",
        "lat_long_source": [31.78, 35.2],
        "lat_long_destination": [37.98, 23.73],
        "distance_km": 1300,
        "timeframe": "~49–52 AD",
        "people_involved": "Paul, Silas, Timothy",
        "scripture_reference": "Acts 15:36–18:22",
    },
    {
        "journey": "Paul's Third Missionary Journey",
        "source_name": "Antioch (Syria)",
        "destination_name": "Ephesus",
        "lat_long_source": [36.2, 36.16],
        "lat_long_destination": [37.95, 27.37],
        "distance_km": 1000,
        "timeframe": "~53–57 AD",
        "people_involved": "Paul",
        "scripture_reference": "Acts 18:23–21:17",
    },
    {
        "journey": "Paul's Journey to Rome",
        "source_name": "Caesarea",
        "destination_name": "Rome",
        "lat_long_source": [32.5, 34.89],
        "lat_long_destination": [41.9, 12.48],
        "distance_km": 2300,
        "timeframe": "~60 AD",
        "people_involved": "Paul, Roman guards, sailors",
        "scripture_reference": "Acts 27–28",
    },
    {
        "journey": "Philip's Journey to Gaza",
        "source_name": "Samaria",
        "destination_name": "Gaza",
        "lat_long_source": [32.22, 35.25],
        "lat_long_destination": [31.5, 34.46],
        "distance_km": 80,
        "timeframe": "~35 AD",
        "people_involved": "Philip",
        "scripture_reference": "Acts 8:26-40",
    },
]
