# Data for biblical travel journeys
biblical_travel_data = [
    {
        "journey": "Abraham's journey to Canaan",
        "source_name": "Ur",
        "destination_name": "Canaan",
        "lat_long_source": [30.9689, 46.0947],
        "lat_long_destination": [31.7683, 35.2137],
        "distance_km": 1600,
        "timeframe": "~2100–2000 BCE",
        "people_involved": "Abraham, Sarah, Lot",
        "scripture_reference": "Genesis 12:1-9",
    },
    {
        "journey": "Israelites' Exodus from Egypt",
        "source_name": "Egypt",
        "destination_name": "Canaan",
        "lat_long_source": [29.8587, 31.1460],
        "lat_long_destination": [31.7683, 35.2137],
        "distance_km": 700,
        "timeframe": "~13th–15th Century BCE",
        "people_involved": "Moses, Israelites",
        "scripture_reference": "Exodus 12:37-51, Numbers 33",
    },
    {
        "journey": "Journey to Mount Sinai",
        "source_name": "Egypt",
        "destination_name": "Mount Sinai",
        "lat_long_source": [29.8587, 31.1460],
        "lat_long_destination": [28.5392, 33.9750],
        "distance_km": 480,
        "timeframe": "~1446 BCE",
        "people_involved": "Moses, Israelites",
        "scripture_reference": "Exodus 19:1-2",
    },
    {
        "journey": "Ruth’s journey to Bethlehem",
        "source_name": "Moab",
        "destination_name": "Bethlehem",
        "lat_long_source": [31.7204, 35.9211],
        "lat_long_destination": [31.7054, 35.2024],
        "distance_km": 50,
        "timeframe": "~1100 BCE",
        "people_involved": "Ruth, Naomi",
        "scripture_reference": "Ruth 1:1-22",
    },
    {
        "journey": "Journey of the Magi",
        "source_name": "Persia/Babylon",
        "destination_name": "Bethlehem",
        "lat_long_source": [32.7578, 44.4152],
        "lat_long_destination": [31.7054, 35.2024],
        "distance_km": 1600,
        "timeframe": "~4 BCE",
        "people_involved": "Magi (Wise Men)",
        "scripture_reference": "Matthew 2:1-12",
    },
    {
        "journey": "Joseph and Mary to Egypt",
        "source_name": "Bethlehem",
        "destination_name": "Egypt",
        "lat_long_source": [31.7054, 35.2024],
        "lat_long_destination": [29.8587, 31.1460],
        "distance_km": 300,
        "timeframe": "~4 BCE",
        "people_involved": "Joseph, Mary, Jesus",
        "scripture_reference": "Matthew 2:13-15",
    },
]
