""" facts from bible """

facts = [
    {
        "Item": "The Earth is Round",
        "Category": "Astronomy",
        "Bible Reference": "Isaiah 40:22",
        "Recorded Timeframe": "~700 BCE",
        "Detail Confirmed by Scientists": True,
        "Scientific Commentary": "Agreed upon during the Renaissance (~1500 CE)",
        "Scientific Comment Year": 1500,
        "Timeframe Difference": "2200 years",
    },
    {
        "Item": "Water Cycle",
        "Category": "Meteorology",
        "Bible Reference": "Ecclesiastes 1:7",
        "Recorded Timeframe": "~935 BCE",
        "Detail Confirmed by Scientists": True,
        "Scientific Commentary": "First described scientifically by Bernard Palissy (1580 CE)",
        "Scientific Comment Year": 1580,
        "Timeframe Difference": "2515 years",
    },
    {
        "Item": "The Earth Hangs on Nothing",
        "Category": "Astronomy",
        "Bible Reference": "Job 26:7",
        "Recorded Timeframe": "~2000-1500 BCE",
        "Detail Confirmed by Scientists": True,
        "Scientific Commentary": "Confirmed by space exploration (20th century)",
        "Scientific Comment Year": 1969,
        "Timeframe Difference": "3500 years",
    },
    {
        "Item": "Paths of the Sea",
        "Category": "Oceanography",
        "Bible Reference": "Psalm 8:8",
        "Recorded Timeframe": "~1000 BCE",
        "Detail Confirmed by Scientists": True,
        "Scientific Commentary": "Matthew Maury discovered ocean currents (1855 CE)",
        "Scientific Comment Year": 1855,
        "Timeframe Difference": "2855 years",
    },
    {
        "Item": "Life is in the Blood",
        "Category": "Biology",
        "Bible Reference": "Leviticus 17:11",
        "Recorded Timeframe": "~1440 BCE",
        "Detail Confirmed by Scientists": True,
        "Scientific Commentary": "William Harvey described blood circulation (1628 CE)",
        "Scientific Comment Year": 1628,
        "Timeframe Difference": "3068 years",
    },
    {
        "Item": "The Stars are Innumerable",
        "Category": "Astronomy",
        "Bible Reference": "Genesis 15:5",
        "Recorded Timeframe": "~2000 BCE",
        "Detail Confirmed by Scientists": True,
        "Scientific Commentary": "Galileo's telescope supported this (~1600 CE)",
        "Scientific Comment Year": 1600,
        "Timeframe Difference": "3600 years",
    },
    {
        "Item": "The Earth is Finite in Age",
        "Category": "Geology",
        "Bible Reference": "Genesis 1:1",
        "Recorded Timeframe": "~2000 BCE",
        "Detail Confirmed by Scientists": True,
        "Scientific Commentary": "Big Bang Theory (20th century)",
        "Scientific Comment Year": 1965,
        "Timeframe Difference": "3965 years",
    },
    {
        "Item": "Disease Transmission by Contact",
        "Category": "Epidemiology",
        "Bible Reference": "Leviticus 13:4-5",
        "Recorded Timeframe": "~1440 BCE",
        "Detail Confirmed by Scientists": True,
        "Scientific Commentary": "Germ theory confirmed (19th century)",
        "Scientific Comment Year": 1860,
        "Timeframe Difference": "3300 years",
    },
    {
        "Item": "Hydrothermal Vents in the Sea",
        "Category": "Oceanography",
        "Bible Reference": "Job 38:16",
        "Recorded Timeframe": "~2000-1500 BCE",
        "Detail Confirmed by Scientists": True,
        "Scientific Commentary": "Discovered in 1977 by scientists",
        "Scientific Comment Year": 1977,
        "Timeframe Difference": "3500 years",
    },
    {
        "Item": "The Expanding Universe",
        "Category": "Cosmology",
        "Bible Reference": "Isaiah 40:22",
        "Recorded Timeframe": "~700 BCE",
        "Detail Confirmed by Scientists": True,
        "Scientific Commentary": "Confirmed by Edwin Hubble (1929 CE)",
        "Scientific Comment Year": 1929,
        "Timeframe Difference": "2629 years",
    },
]
